language: c
env:
  - PERL_CPANM_OPT="--mirror http://cpan.cpantesters.org"
install:
  # Install newer version of Valgrind from custom repo so Test::Nginx's
  # num-callers works: https://github.com/openresty/test-nginx/pull/17
  - sudo add-apt-repository -y ppa:jtaylor/jtaylor
  - sudo apt-get update -q
  - sudo apt-get -y install valgrind
script:
  - make grind
